### ISSUE TITLE
Add a place holder card and bottom nav

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/solar-flare#7]
It would be awesome if I can get some help with this, I am really busy with Ara, so place holder stuff will save me a lot of time.

**Comment by AlecsisDuarte** [comment]
Hi, I would like to work with this issue if possible.

**Comment by FultonBrowne** [comment]
Thanks @AlecsisDuarte , that would be awsome

**Comment by AlecsisDuarte** [comment]
Great!

Before I begin I would like to know:
- What would you like the placeholder(s) to show?
- And what would the different actions on the bottom navigation be?

**Comment by FultonBrowne** [comment]
@AlecsisDuarte how about a sample text and image for the list and stocks, pay, and crypto for the bottom nav

**Comment by AlecsisDuarte** [comment]
Sure thing!
I will try to publish something this weekend for you to review.

**Comment by FultonBrowne** [comment]
thanks @AlecsisDuarte

**Comment by AlecsisDuarte** [comment]
Hi @FultonBrowne here is an update #10, let me know if you want me to **change anything**

![Preview](https://user-images.githubusercontent.com/18224162/67746666-2c251c00-f9e4-11e9-86ad-9d47145918c1.png)

**Comment by FultonBrowne** [comment]
That looks great, thanks @AlecsisDuarte

**Comment by AlecsisDuarte** [comment]
Awesome!
